Applications:
  - name: "app82"
    displayName: "myAppName app82"
    discoveryURL: "http://localhost:8080/"
    replyURLs:
    - 'http://localhost:8080/auth/openid/callback'
    - 'https://basta.dev-gke.nais.io/auth/openid/callback'
    owners:
    - 'username1@sindretest.onmicrosoft.com'
