Applications:
  - name: "app18"
    replyURLs:
    - 'https://localhost/callback'
    owners:
    - 'username1@sindretest.onmicrosoft.com'
    - 'username2@sindretest.onmicrosoft.com'
  - name: "app19"
    replyURLs:
    - 'http://localhost:8080/auth/openid/callback'
    owners:
    - 'username1@sindretest.onmicrosoft.com'
  - name: "app20"
    replyURLs:
    - 'http://localhost:8080/auth/openid/callback'
    - 'https://basta.dev-gke.nais.io/auth/openid/callback'
    owners:
    - 'username1@sindretest.onmicrosoft.com'
  
